{% set name = "ivmodels" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ivmodels-{{ version }}.tar.gz
  sha256: e65ab15ae933e109c8e78bb8914a8730d36f42aa79418ab802c08760c19ba5fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - wheel
    - poetry-core
    - pip
  run:
    - python >=3.7
    - numpy
    - scikit-learn
    - glum
    - scipy
  run_constrained:
    - sphinx >=3.0.0,<4.0.0
    - sphinx-autodoc-typehints >=1.11.1,<2.0.0

test:
  imports:
    - ivmodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mlondschien/ivmodels
  summary: IV Models
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ivmodels.readthedocs.io/
  dev_url: https://github.com/mlondschien/ivmodels

extra:
  recipe-maintainers:
    - mlondschien
